#!/usr/bin/env bash


case "$1" in 
    help)
	echo 
	echo "DOOM - Local Linux Automation"
	echo
	echo "Usage:"
	echo "   doom <command>"
	echo
	echo "Commands: "
	echo "		start		Start a project environment"
	echo "		stop 		Stop a project environment"
	echo "		save		Save current session"
	echo "		restore		Restore previous session"
	echo "		status		Show current state"
	echo "		run		Execute an approved action"
	echo "		learn		Create a new automation"
	;;


    start)
	if [ -z "$2" ]; then 
	        echo "Usage: doom start <project>"
	       	exit 1
	fi
	
	project="$2"
	project_file="$HOME/Documents/neer/doom/projects/$project.yaml"
	
	if [ ! -f "$project_file" ]; then
			echo "Project $project does not exist."
			exit 1
	fi

	echo "Starting DOOM project: $project"
	echo "Configuration: $project_file"
	;; 	

    *)
	echo "Unknown command: '$1'"
	echo "Run 'doom help' for available commands."
	exit 1
	;;
esac

